name: Lint Code Base

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Super-Linter
      uses: github/super-linter@v4.9.7
